version: '3.8'

services:
  app:
    image: node:latest
    working_dir: /app
    volumes:
      - .:/app
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run build && npm start"
