services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kutay-portfolio
    ports:
      - "3001:3001"
    restart: always
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s